#ifndef GUARD_BOND_OF_EIRE_OBJECTS_H
#define GUARD_BOND_OF_EIRE_OBJECTS_H

// --- Standard Local IDs ---
#define LOCALID_FRONTIER_MART_CLERK 1
#define LOWER_TOWER_LOBBY_REPORTER 5

// --- Gabby and Ty Route Constants ---
#define LOCALID_ROUTE111_GABBY_1 1
#define LOCALID_ROUTE111_TY_1    2
#define LOCALID_ROUTE111_GABBY_2 2
#define LOCALID_ROUTE111_TY_2    3
#define LOCALID_ROUTE111_GABBY_3 2
#define LOCALID_ROUTE111_TY_3    3

#define LOCALID_ROUTE118_GABBY_1 1
#define LOCALID_ROUTE118_TY_1    2
#define LOCALID_ROUTE118_GABBY_2 2
#define LOCALID_ROUTE118_TY_2    3
#define LOCALID_ROUTE118_GABBY_3 2
#define LOCALID_ROUTE118_TY_3    3

#define LOCALID_ROUTE120_GABBY_1 1
#define LOCALID_ROUTE120_TY_1    2
#define LOCALID_ROUTE120_GABBY_2 2
#define LOCALID_ROUTE120_TY_2    3

#define LOCALID_SLATEPORT_ENERGY_GURU 1

// --- Contest Contestant Constants ---
// Safe high IDs to prevent black-screen initialization crashes
#define LOCALID_CONTESTANT_1 100
#define LOCALID_CONTESTANT_2 101
#define LOCALID_CONTESTANT_3 102
#define LOCALID_CONTESTANT_4 103

#endif // GUARD_BOND_OF_EIRE_OBJECTS_H
